title = "develop config"

[http]
host = "0.0.0.0"
port = "8000"

[work]
path = "E:/itemtest/github.com/ginweb/server"

[log]
path = "log/server.log"

[mysql]
host = "localhost"
port = "3306"
username = "root"
password = ""
maxOpenConns = 50
maxIdleConns = 10
maxLifetime = 3600
maxIdleTime = 600

[redis]
host = "192.168.1.14:6379"
password = ""
poolSize = 50
maxIdleConns = 50
minIdleConns = 20
db = 0
