PROJECT_NAME:="main-server"

.PHONY: build start restart stop clean

build:
	bash build.sh compile ${PROJECT_NAME}


start:
	bash build.sh start ${PROJECT_NAME}


restart:
	bash build.sh restart ${PROJECT_NAME}


stop:
	bash build.sh stop ${PROJECT_NAME}


clean:
	bash build.sh clean ${PROJECT_NAME}
